// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuTFeXrPWAItjL72QMdPMtKJnNRVELmys',
    appId: '1:155505566855:web:c603280204ddb9d80ac422',
    messagingSenderId: '155505566855',
    projectId: 'foodpark-setup',
    authDomain: 'foodpark-setup.firebaseapp.com',
    storageBucket: 'foodpark-setup.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzK__AabbW6ieX08R-wTBaNCU7U3lmW1M',
    appId: '1:155505566855:android:fe8b19508e04837f0ac422',
    messagingSenderId: '155505566855',
    projectId: 'foodpark-setup',
    storageBucket: 'foodpark-setup.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3ZIJbjg1f9Kd68G_dt2u_WPzFtH-M4qo',
    appId: '1:155505566855:ios:886a53b9c1e9deea0ac422',
    messagingSenderId: '155505566855',
    projectId: 'foodpark-setup',
    storageBucket: 'foodpark-setup.appspot.com',
    iosClientId: '155505566855-hsbqmi6ih44r5fml9i628jj76ticd0kp.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodpark',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3ZIJbjg1f9Kd68G_dt2u_WPzFtH-M4qo',
    appId: '1:155505566855:ios:886a53b9c1e9deea0ac422',
    messagingSenderId: '155505566855',
    projectId: 'foodpark-setup',
    storageBucket: 'foodpark-setup.appspot.com',
    iosClientId: '155505566855-hsbqmi6ih44r5fml9i628jj76ticd0kp.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodpark',
  );
}
